# Generated by Django 5.0.3 on 2024-03-14 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),  # 'accounts' 앱의 초기 마이그레이션에 의존합니다.
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Profile 데이터를 옮깁니다.
            INSERT INTO accounts_profile (
                id,
                user_id,
                nickname,
                profile_photo
            )
            SELECT
                id,
                user_id,
                nickname,
                profile_photo
            FROM
                blog_profile;
        """,
            reverse_sql="""
            -- 역 마이그레이션을 위한 Profile 데이터 이동
            INSERT INTO blog_profile (
                id,
                user_id,
                nickname,
                profile_photo
            )
            SELECT
                id,
                user_id,
                nickname,
                profile_photo
            FROM
                accounts_profile;
        """,
        ),
        migrations.RunSQL(
            """
            -- Photo 데이터를 옮깁니다.
            INSERT INTO accounts_photo (
                id,
                image,
                user_id,
                content,
                created_at,
                updated_at,
                is_public
            )
            SELECT
                id,
                image,
                user_id,
                content,
                created_at,
                updated_at,
                is_public
            FROM
                blog_photo;
        """,
            reverse_sql="""
            -- 역 마이그레이션을 위한 Photo 데이터 이동
            INSERT INTO blog_photo (
                id,
                image,
                user_id,
                content,
                created_at,
                updated_at,
                is_public
            )
            SELECT
                id,
                image,
                user_id,
                content,
                created_at,
                updated_at,
                is_public
            FROM
                accounts_photo;
        """,
        ),
    ]
