# Generated by Django 5.0.3 on 2024-03-11 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_recomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReComment',
        ),
    ]
