# Generated by Django 5.0.3 on 2024-03-11 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
