# Generated by Django 5.0.3 on 2024-03-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_profilethumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilethumbnail',
            name='image',
            field=models.ImageField(upload_to='blog/images/thumbnail/%Y/%m/%d/'),
        ),
    ]
