# Generated by Django 5.0.3 on 2024-03-12 12:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_profilethumbnail_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileThumbnail',
            new_name='Photo',
        ),
    ]
