# Generated by Django 5.0.3 on 2024-03-14 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0016_alter_photo_image_alter_photo_user_and_more"),
        ("accounts", "0002_auto_20240314_2124"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="user",
        ),
        migrations.DeleteModel(
            name="Photo",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
